### ISSUE TITLE
Native FIL support to showcase FILSnap usage in a dapp

### ISSUE THREAD

**Issue by bmann** [FundRing/fundring#5]
Currently FEVM-compatible wallets are used to interact with the app, and FEVM smart contracts are deployed by project maintainers.

With [FILSnap](https://filsnap.fission.app/) being available for MetaMask, we can showcase this support as well as support any other native FIL wallets (Brave, FILFox?) for funding.

* Make UI / navigation to "fund with native FIL wallet"
* Page at `/filfund/` or similar which has the functionality

This also opens up a place for other native Fil functions, like vesting and multisigs.

**Comment by avivash** [comment]
I've got this deployed to a [staging domain](https://fundring-filsnap.fission.app/) for now.

https://www.loom.com/share/80c56f24347846e59af5eb968b37e899?sid=7cc6edb7-7fd7-4db5-b912-3be6796809a6

PR is up [here](https://github.com/FundRing/fundring/pull/8)

**Comment by walkah** [comment]
PR available: https://github.com/FundRing/fundring/pull/8

**Comment by avivash** [comment]
Deployed
